# Generated by Django 4.2.2 on 2023-06-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactEnquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='user_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='contactEnquiry/'),
        ),
    ]
